credenziali = "statistiche04"

[connections.datitreni]
dialect = "mysql"
driver = "pymysql"
host = "194.76.118.27"
database = "hjqplcyi_datitreni"
username = "hjqplcyi_lettura_dati"
password = "TqBY,Y{dB8$D"